#!/usr/bin/env bash
#information abd the domain and subdomain

url=""
domain=$2
sub=$1
url+="$sub"
url+="."
url+="$domain"
type=""

#ipp=`dig $domain | awk "NR==14{ print }" | cut -f5 -d$'\t'`

run()
{
    ipp=`dig $domain | awk "NR==14{ print }" | cut -f5 -d$'\t'`
    type=`dig www.$2 | awk "NR==14{ print }" | cut -f4 -d$'\t'`
    echo "The subdomain www is a $type record and points to $ipp"
    type=`dig lb-01.$2 | awk "NR==14{ print }" | cut -f4 -d$'\t'`
    echo "The subdomain lb-01 is a $type record and points to $ipp"
    type=`dig web-01.$2 | awk "NR==14{ print }" | cut -f4 -d$'\t'`
    echo "The subdomain web-01 is a $type record and points to $ipp"
    type=`dig web-02.$2 | awk "NR==14{ print }" | cut -f4 -d$'\t'`
    echo "The subdomain web-02 is a $type record and points to $ipp"
}
if [ $# -lt 2 ]; then
    run
else
    type=`dig $url | awk "NR==14{ print }" | cut -f4 -d$'\t'`
    ip=`dig $url | awk "NR==14{ print }" | cut -f5 -d$'\t'`
    echo "The subdomain $sub is a $type record and points to $ip"
fi
