#!/usr/bin/env bash
#information abd the domain and subdomain

url=""
domain=$2
sub=$1
url+="$sub"
url+="."
url+="$domain"
type=""
type=`dig $url | awk "NR==14{ print }" | cut -f4 -d$'\t'`
ip=`dig $url | awk "NR==14{ print }" | cut -f5 -d$'\t'`

echo "The subdomain $sub is a $type record and points to $ip"
