#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server:

file=$1 
ip=$2
user=$3
prk=$4

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i $prk -o StrictHostKeyChecking=no $file $user@$ip:~/ 
