#!/usr/bin/env bash


sudo apt-get update
sudo apt-get install nginx
sudo /etc/init.d/nginx start
sudo chmod 777 /var/www/html/inde
x.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html

