#!/usr/bin/env bash
#INstall NGINX and configue the default html page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 777 /var/www/html/inde
x.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html

