#!/usr/bin/env bash
# Configure a 301 permanent reidrection

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
dest="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "22i $dest" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
