#!/usr/bin/env bash
# script to link sites-enabled to sites-available and start nginx without running status
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
systemctl daemon-reload
systemctl start nginx
