#!/usr/bin/env bash
#print Holberton School 10 times

i=0
while [ "$i" -lt "10" ]
do
	echo "Holberton School"
	((i++))
done
#second method
#i=0
#while ((i < 10))
#do 
#echo "Holberton School"
#((i++))
#done
