#!/usr/bin/env bash
#check for file

file="holbertonschool"
if [ -e "$file" ]
then
	echo "$file file exists"
	if [ -s "$file" ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	 echo "holbertonschool file does not exist"
fi
